vim.opt.tabstop = 4
vim.opt.softtabstop = 0
vim.opt.expandtab = true
vim.opt.shiftwidth = 4
vim.opt.smarttab = true
vim.opt.smartcase = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.autowrite = true
vim.opt.clipboard = "unnamedplus"
vim.opt.confirm = true
vim.opt.hlsearch = true
vim.opt.cursorline = true
vim.opt.grepformat = "%f:%l:%c:%m"
vim.opt.grepprg = "rg --vimgrep"
vim.opt.list = true -- Show some invisible characters (tabs...
vim.opt.mouse = "a" -- Enable mouse mode
vim.opt.scrolloff = 4 -- Lines of context
vim.opt.signcolumn = "yes"
vim.opt.smartindent = true
vim.opt.termguicolors = true
vim.opt.splitbelow = true -- Put new windows below current
vim.opt.splitright = true -- Put new windows right of current
vim.opt.timeoutlen = 300
vim.opt.undofile = true
vim.opt.undolevels = 10000
vim.opt.wrap = false -- Disable line wrap
vim.opt.splitkeep = "screen"
vim.opt.shell = "zsh"
